name: .NET Core 2.0

on: [push, pull_request]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macOS-latest']
        sdk: ['2.1.202']
        config: ['Debug', 'Release']
        target:
          - 'netcoreapp2.0'

          - 'netstandard2.0'
          - 'netstandard1.6'
          - 'netstandard1.5'
          - 'netstandard1.4'
          - 'netstandard1.3'
          - 'netstandard1.2'
          - 'netstandard1.1'
          - 'netstandard1.0'
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup .netcore sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.sdk }}
      - name: show info
        run: |
          echo sdk version
          dotnet --version
          echo branch '${{ github.ref }}', os '${{ matrix.os }}', sdk '${{ matrix.sdk }}', target '${{ matrix.target }}', config '${{ matrix.config }}'
          git log -3
      - name: build
        run: dotnet build LeeVox.Sdk -f ${{ matrix.target }} -c ${{ matrix.config }} /p:TargetFrameworks=${{ matrix.target }}
      - name: test
        if: startsWith(matrix.target, 'netcoreapp')
        run: dotnet test LeeVox.Sdk.Test -f ${{ matrix.target }} -c ${{ matrix.config }} /p:TargetFrameworks=${{ matrix.target }} /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/Coverage/
      - name: upload code coverage
        if: startsWith(matrix.target, 'netcoreapp')
        continue-on-error: true
        run: |
          chmod +x $CODECOV
          $CODECOV -B $GITHUB_REF -n "os $OS - sdk $SDK - target $TARGET - config $CONFIG"
        shell: sh -e {0}
        env:
          OS: ${{ matrix.os }}
          SDK: ${{ matrix.sdk }}
          TARGET: ${{ matrix.target }}
          CONFIG: ${{ matrix.config }}
          CODECOV: ${{ github.workspace }}/.github/workflows/codecov.sh
