name: release

on:
  push:

jobs:
  main:
    env:
      VERSION: "5.0"
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        sdk: ['5.0.100']
        config: ['Release']
        target: ['net5']
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup .netcore sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.sdk }}
      - name: show info
        run: |
          echo sdk version
          dotnet --version
          echo branch '${{ github.ref }}', os '${{ matrix.os }}', sdk '${{ matrix.sdk }}', target '${{ matrix.target }}', config '${{ matrix.config }}'
          git log -3
      - name: build
        run: dotnet build LeeVox.Sdk -f ${{ matrix.target }} -c ${{ matrix.config }} /p:TargetFrameworks=${{ matrix.target }}
      - name: get patch version
        id: get-patch-version
        shell: pwsh
        run: |
          '::set-output name=PATCH::' + [math]::Round( ((Get-Date) - (Get-Date -Date "1/1/2020 0:0:0")).TotalMinutes / 2)
      - name: pack
        run: dotnet pack LeeVox.Sdk -c ${{ matrix.config }} /p:TargetFrameworks=${{ matrix.target }} /p:Version=$VERSION.${{ steps.get-patch-version.outputs.PATCH }}
      - name: create release
        uses: actions/create-release@v1
        with:
          tag_name: v$VERSION.${{ steps.get-patch-version.outputs.PATCH }}
          release_name: Version $VERSION.${{ steps.get-patch-version.outputs.PATCH }}
          draft: false
          pre_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}