resources:
- repo: self
  fetchDepth: 5

jobs:
- template: .azure-pipelines.netcoreapp.yml
  parameters:
    name: netcoreapp1_1
    sdk: '1.1.11'
    target: netcoreapp1.1
    publishTest: false

- template: .azure-pipelines.netcoreapp.yml
  parameters:
    name: netcoreapp2_1
    sdk: '2.1.500'
    target: netcoreapp2.1


- template: .azure-pipelines.netstandard.yml
  parameters:
    name: netstandard1_6
    sdk: '1.1.11'
    target: 'netstandard1.6'

- template: .azure-pipelines.netstandard.yml
  parameters:
    name: netstandard2_0
    sdk: '2.1.500'
    target: 'netstandard2.0'