parameters:
  name: ''
  sdk: ''
  target: ''
  publishTest: true

jobs:
- job: ${{ parameters.name }}
  variables:
    TargetFramework: ${{ parameters.target }}
  steps:
  - script: 'git log -3'
    displayName: 'show git log'

  - task: DotNetCoreInstaller@0
    displayName: 'Install SDK'
    inputs:
      version: ${{ parameters.sdk }}

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: LeeVox.Sdk.Test/LeeVox.Sdk.Test.csproj
      arguments: /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestCoverageResult
      publishTestResults: ${{ parameters.publishTest }}
      workingDirectory: $(System.DefaultWorkingDirectory)

  - script: 'type "$(System.DefaultWorkingDirectory)/TestCoverageResult/.cobertura.xml"'
    displayName: 'show coverage'

  - bash: 'bash <(curl -s https://codecov.io/bash) -s TestCoverageResult -B $(Build.SourceBranchName) -n "$(Agent.OS) - sdk ${{ parameters.sdk }} - target ${{ parameters.target }}"'
    displayName: 'publish codecov'
    condition: ${{ parameters.publishTest }}
    workingDirectory: $(System.DefaultWorkingDirectory)
