variables:
  OS: 'osx'

  SDK1_0: '1.1.11'
  SDK1_1: '1.1.11'
  SDK2_0: '2.1.202'
  SDK2_1: '2.1.500'
  SDK2_2: '2.2.100'
  SDK3_0: '3.0.100-preview-009812'

  NETCOREAPP1_0: 'netcoreapp1.0'
  NETCOREAPP1_1: 'netcoreapp1.1'
  NETCOREAPP2_0: 'netcoreapp2.0'
  NETCOREAPP2_1: 'netcoreapp2.1'
  NETCOREAPP2_2: 'netcoreapp2.2'
  NETCOREAPP3_0: 'netcoreapp3.0'

  NETSTANDARD1_0: 'netstandard1.6'
  NETSTANDARD2_0: 'netstandard2.0'

jobs:
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore1_0
    sdk: $(SDK1_0)
    variables:
      PUBLISH_TEST_RESULT: false
    targets:
      netcoreapp1_0:
        TEST_TARGET: $(NETCOREAPP1_0)
        BUILD_TARGET: $(NETCOREAPP1_0)
      netstandard1_0:
        BUILD_TARGET: $(NETSTANDARD1_0)
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore1_1
    sdk: $(SDK1_1)
    variables:
      PUBLISH_TEST_RESULT: false
    targets:
      netcoreapp1_1:
        TEST_TARGET: $(NETCOREAPP1_1)
        PUBLISH_TEST_RESULT: false
        BUILD_TARGET: $(NETCOREAPP1_1)
      netcoreapp1_0:
        TEST_TARGET: $(NETCOREAPP1_0)
        BUILD_TARGET: $(NETCOREAPP1_0)
      netstandard1_0:
        BUILD_TARGET: $(NETSTANDARD1_0)
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore2_0
    sdk: $(SDK2_0)
    targets:
      netcoreapp2_0:
        TEST_TARGET: $(NETCOREAPP2_0)
        BUILD_TARGET: $(NETCOREAPP2_0)
      netstandard2_0:
        BUILD_TARGET: $(NETSTANDARD2_0)
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore2_1
    sdk: $(SDK2_1)
    targets:
      netcoreapp2_1:
        TEST_TARGET: $(NETCOREAPP2_1)
        BUILD_TARGET: $(NETCOREAPP2_1)
      netcoreapp2_0:
        TEST_TARGET: $(NETCOREAPP2_0)
        BUILD_TARGET: $(NETCOREAPP2_0)
      netstandard2_0:
        BUILD_TARGET: $(NETSTANDARD2_0)
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore2_2
    sdk: $(SDK2_2)
    targets:
      netcoreapp2_2:
        TEST_TARGET: $(NETCOREAPP2_2)
        BUILD_TARGET: $(NETCOREAPP2_2)
      netcoreapp2_1:
        TEST_TARGET: $(NETCOREAPP2_1)
        BUILD_TARGET: $(NETCOREAPP2_1)
      netcoreapp2_0:
        TEST_TARGET: $(NETCOREAPP2_0)
        BUILD_TARGET: $(NETCOREAPP2_0)
      netstandard2_0:
        BUILD_TARGET: $(NETSTANDARD2_0)
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore3_0
    sdk: $(SDK3_0)
    targets:
      netcoreapp3_0:
        TEST_TARGET: $(NETCOREAPP3_0)
        BUILD_TARGET: $(NETCOREAPP3_0)
      netstandard2_0:
        BUILD_TARGET: $(NETSTANDARD2_0)