resources:
- repo: self
  fetchDepth: 5

jobs:
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore1_0
    sdk: '1.1.11'
    matrix:
      netcoreapp1_0:
        TargetFramework: 'netcoreapp1.0'
        publishTest: false
      netstandard1_6:
        TargetFramework: 'netstandard1.6'
        execTest: false

- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore1_1
    sdk: '1.1.11'
    matrix:
      netcoreapp1_1:
        TargetFramework: 'netcoreapp1.1'
        publishTest: false
      netstandard1_6:
        TargetFramework: 'netstandard1.6'
        execTest: false

- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore2_0
    sdk: '2.1.202'
    matrix:
      netcoreapp2_0:
        TargetFramework: 'netcoreapp2.0'
      netstandard1_6:
        TargetFramework: 'netstandard1.6'
        execTest: false
      netstandard2_0:
        TargetFramework: 'netstandard2.0'
        execTest: false

- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore2_1
    sdk: '2.1.500'
    matrix:
      netcoreapp2_1:
        TargetFramework: 'netcoreapp2.1'
      netstandard1_6:
        TargetFramework: 'netstandard1.6'
        execTest: false
      netstandard2_0:
        TargetFramework: 'netstandard2.0'
        execTest: false

- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore2_2
    sdk: '2.2.100'
    matrix:
      netcoreapp2_2:
        TargetFramework: 'netcoreapp2.2'
      netstandard1_6:
        TargetFramework: 'netstandard1.6'
        execTest: false
      netstandard2_0:
        TargetFramework: 'netstandard2.0'
        execTest: false

- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcore3_0
    sdk: '3.0.100-preview-009812'
    matrix:
      netcoreapp3_0:
        TargetFramework: 'netcoreapp3.0'
      netstandard1_6:
        TargetFramework: 'netstandard1.6'
        execTest: false
      netstandard2_0:
        TargetFramework: 'netstandard2.0'
        execTest: false