resources:
- repo: self
  fetchDepth: 5

jobs:
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcoreapp1_0
    sdk: '1.1.11'
    target: 'netcoreapp1.0'
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcoreapp1_1
    sdk: '1.1.11'
    target: 'netcoreapp1.1'
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcoreapp2_0
    sdk: '2.1.202'
    target: 'netcoreapp2.0'
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcoreapp2_1
    sdk: '2.1.500'
    target: 'netcoreapp2.1'
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcoreapp2_2
    sdk: '2.2.100'
    target: 'netcoreapp2.2'
- template: .azure-pipelines.buildandtest.yml
  parameters:
    name: netcoreapp3_0
    sdk: '3.0.100-preview-009812'
    target: 'netcoreapp3.0'