parameters:
  name: ''
  sdk: ''
  matrix:

jobs:
- job: ${{ parameters.name }}
  variables:
    execTest: true
    publishTest: true
  strategy:
    matrix: ${{ parameters.matrix }}
  steps:
  - script: 'git log -3'
    displayName: 'show git log'

  - task: DotNetCoreInstaller@0
    displayName: 'Install SDK'
    inputs:
      version: ${{ parameters.sdk }}

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    condition: $(execTest)
    inputs:
      command: test
      projects: LeeVox.Sdk.Test/LeeVox.Sdk.Test.csproj
      arguments: /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResult/Coverage/'
      publishTestResults: $(publishTest)

  - bash: 'bash <(curl -s https://codecov.io/bash) -B $(Build.SourceBranchName) -n "$(Agent.OS) - sdk ${{ parameters.sdk }}"'
    displayName: 'publish codecov'
    condition: $(publishTest)