parameters:
  name: ''
  sdk: ''
  target: ''

jobs:
- job: ${{ parameters.name }}
  variables:
    Configuration: DEBUG
    TargetFramework: ${{ parameters.target }}
  steps:
  - script: 'git log -3'
    displayName: 'show git log'

  - task: DotNetCoreInstaller@0
    displayName: 'Install SDK'
    inputs:
      version: ${{ parameters.sdk }}

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: LeeVox.Sdk.Test/LeeVox.Sdk.Test.csproj
      arguments: /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResult/Coverage/'