resources:
- repo: self
  fetchDepth: 5
phases:
- phase: netcoreapp1.0
  condition: succeededOrFailed()
  variables:
    Configuration: DEBUG+RELEASE
    TargetFramework: netcoreapp1.0
  steps:
  - script: 'git log -3'
    displayName: 'show git log'

  - task: DotNetCoreInstaller@0
    displayName: 'Install SDK'
    inputs:
      version: 1.1.11

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: LeeVox.Sdk.Test

- phase: netcoreapp1.1
  condition: succeededOrFailed()
  variables:
    Configuration: DEBUG+RELEASE
    TargetFramework: netcoreapp1.1
  steps:
  - script: 'git log -3'
    displayName: 'show git log'

  - task: DotNetCoreInstaller@0
    displayName: 'Install SDK'
    inputs:
      version: 1.1.11

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: LeeVox.Sdk.Test

- phase: netcoreapp2.0
  condition: succeededOrFailed()
  variables:
    Configuration: DEBUG+RELEASE
    TargetFramework: netcoreapp2.0
  steps:
  - script: 'git log -3'
    displayName: 'show git log'

  - task: DotNetCoreInstaller@0
    displayName: 'Install SDK'
    inputs:
      version: 2.1.202

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: LeeVox.Sdk.Test

- phase: netcoreapp2.1
  condition: succeededOrFailed()
  variables:
    Configuration: DEBUG+RELEASE
    TargetFramework: netcoreapp2.1
  steps:
  - script: 'git log -3'
    displayName: 'show git log'

  - task: DotNetCoreInstaller@0
    displayName: 'Install SDK'
    inputs:
      version: 2.1.500

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: LeeVox.Sdk.Test